"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const clienteModelo_1 = __importDefault(require("../modelos/clienteModelo"));
const enderecoModelo_1 = __importDefault(require("../modelos/enderecoModelo"));
const telefoneModelo_1 = __importDefault(require("../modelos/telefoneModelo"));
let cliente = new clienteModelo_1.default();
cliente.nome = `ian machado`;
cliente.nomeSocial = `indio`;
cliente.dataCadastro = new Date(2012, 6, 23);
cliente.dataNascimento = new Date(2004, 19, 2);
let telefone = new telefoneModelo_1.default();
telefone.ddd = "012";
telefone.numero = "12988899743";
cliente.telefones.push(telefone);
let telefone2 = new telefoneModelo_1.default();
telefone2.ddd = "012";
telefone2.numero = "39051008";
cliente.telefones.push(telefone2);
let endereco = new enderecoModelo_1.default();
endereco.rua = `Rua pureza alves dos santos`;
endereco.bairro = `são josé dos campos`;
endereco.pais = `Brasil`;
endereco.codigoPostal = `12247120`;
cliente.endereco = endereco;
let dependente = new clienteModelo_1.default();
dependente.nome = `Ian Ferreira`;
dependente.nomeSocial = `ian indio`;
dependente.dataCadastro = new Date(2010, 10, 12);
dependente.dataNascimento = new Date(2004, 2, 19);
dependente.endereco = cliente.endereco.clonar();
dependente.telefones = cliente.telefones.map(telefone => telefone.clonar());
dependente.titular = cliente;
cliente.dependentes.push(dependente);
console.log("\nCLIENTES\n-----------------------------------");
console.log(cliente);
console.log("\nDEPENDENTES\n-----------------------------------");
console.log(dependente);
