"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var clienteModelo_1 = require("../modelos/clienteModelo");
var enderecoModelo_1 = require("../modelos/enderecoModelo");
var telefoneModelo_1 = require("../modelos/telefoneModelo");
var cliente = new clienteModelo_1.default();
cliente.nome = "ian machado";
cliente.nomeSocial = "indio";
cliente.dataCadastro = new Date(2012, 6, 23);
cliente.dataNascimento = new Date(2004, 19, 2);
var telefone = new telefoneModelo_1.default();
telefone.ddd = "012";
telefone.numero = "12988899743";
cliente.telefones.push(telefone);
var telefone2 = new telefoneModelo_1.default();
telefone2.ddd = "012";
telefone2.numero = "39051008";
cliente.telefones.push(telefone2);
var endereco = new enderecoModelo_1.default();
endereco.rua = "Rua pureza alves dos santos";
endereco.bairro = "s\u00E3o jos\u00E9 dos campos";
endereco.pais = "Brasil";
endereco.codigoPostal = "12247120";
cliente.endereco = endereco;
var dependente = new clienteModelo_1.default();
dependente.nome = "Ian Ferreira";
dependente.nomeSocial = "ian indio";
dependente.dataCadastro = new Date(2010, 10, 12);
dependente.dataNascimento = new Date(2004, 2, 19);
dependente.endereco = cliente.endereco.clonar();
dependente.telefones = cliente.telefones.map(function (telefone) { return telefone.clonar(); });
dependente.titular = cliente;
cliente.dependentes.push(dependente);
console.log("\nCLIENTES\n-----------------------------------");
console.log(cliente);
console.log("\nDEPENDENTES\n-----------------------------------");
console.log(dependente);
